/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_appsync_graphqlEndpoint": "https://lx64jks4ljb5dijum53asoesqe.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xj5vz222vjbzfmnulw7zhu746e",
    "aws_cognito_identity_pool_id": "eu-west-3:ed829579-8cfc-4c7e-8783-d4b1560214f0",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_faaiQA5A6",
    "aws_user_pools_web_client_id": "1jct2dmi0c39jl5rng26rg4p1j",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "bouhet-storage-dd5bz7zt1xiqq155941-dev",
    "aws_user_files_s3_bucket_region": "eu-west-3"
};


export default awsmobile;
